jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug API Key
        run: echo "API Key Length: ${#API_KEY}"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run Streamlit App
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Pass secret here
  
