name: Debug API Key

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug API Key
        run: |
          if [ -z "$API_KEY" ]; then
            echo "❌ API Key is NOT set!"
            exit 1
          else
            echo "✅ API Key is set. Length: ${#API_KEY}"
            echo "🔍 First 4 characters: ${API_KEY:0:4}"  # Should show "hf_y"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}
