name: Deploy Streamlit App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}  # ✅ Set API key globally

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug API Key
        run: |
          echo "API Key Length: ${#API_KEY}"
          echo "First 4 characters: ${API_KEY:0:4}"  # Should be "hf_y"
