name: Deploy Streamlit App

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Debug API Key
        run: |
          if [ -z "$API_KEY" ]; then
            echo "❌ API Key is missing!"
            exit 1
          else
            echo "✅ API Key is set. Length: ${#API_KEY}"
            echo "🔍 First 4 characters: ${API_KEY:0:4}"  # Should show "hf_Y"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}
