jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Debug API Key
        run: echo "API Key Length: ${#API_KEY}"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run Streamlit App
        working-directory: llm
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Pass secret here
  
